# Generated by Django 2.1.4 on 2018-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=8, verbose_name='USGS Site ID')),
                ('name', models.CharField(max_length=200, verbose_name='Site Name')),
                ('weather_url', models.URLField(blank=True, null=True, verbose_name='Weather URL')),
                ('upper_level', models.FloatField(blank=True, null=True, verbose_name='Upper Level')),
                ('lower_level', models.FloatField(blank=True, null=True, verbose_name='Lower Level')),
                ('river_class', models.CharField(blank=True, max_length=5, null=True, verbose_name='Class')),
                ('travel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Travel')),
                ('latest_height', models.FloatField(blank=True, null=True, verbose_name='Latest Height')),
                ('latest_flow', models.IntegerField(blank=True, null=True, verbose_name='Latest Flow')),
                ('weather_locale', models.CharField(blank=True, max_length=200, null=True, verbose_name='Weather Locale')),
                ('aw_url', models.URLField(blank=True, null=True, verbose_name='American Whitewater URL')),
                ('height_change', models.FloatField(blank=True, null=True, verbose_name='Change in height')),
                ('flow_change', models.IntegerField(blank=True, null=True, verbose_name='Change in flow')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('state', models.CharField(choices=[('PA', 'Pennsylvania'), ('MD', 'Maryland'), ('VA', 'Virginia'), ('WV', 'West Virginia')], max_length=2, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=True)),
            ],
        ),
    ]
